name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Files
        run: |
          ls -R

      - name: Run tests.sh
        run: |
          ./project/tests.sh
