name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Working Directory
        working-directory: ./project

      - name: Run tests.sh
        run: |
          chmod +x project/tests.sh
          project/tests.sh
