name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run tests.sh
        working-directory: ./project
        run: |
          chmod +x tests.sh
          ./tests.sh
